apiVersion: v1
kind: Pod
metadata:
  name: po-vol-cm
spec:
  volumes:
  - name: confm
    configMap:
      name: my-cm
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: confm
      mountPath: /mydata
