apiVersion: v1
kind: Pod
metadata:
  name: my-pod-env-secrets
spec:
  containers:
  - image: nginx
    name: nginx
    env:
    - name: myusername
      valueFrom:
        secretKeyRef:
          name: my-secrets
          key: username
    - name: mypassword
      valueFrom:
        secretKeyRef:
          name: my-secrets
          key: password