apiVersion: v1
kind: Pod
metadata:
  name: po-vol-secrets
spec:
  volumes:
  - name: secrets
    secret:
      secretName: my-secrets
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: secrets
      mountPath: /mydata
